# Generated by Django 4.2.4 on 2023-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('1', 'BMW'), ('2', 'AUDI'), ('3', 'VOLKSWAGEN')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('1', 'X5'), ('2', 'X6'), ('3', 'X7'), ('4', 'A5'), ('5', 'A7'), ('6', 'A8'), ('7', 'Polo'), ('8', 'Golf'), ('9', 'Passat')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '2021'), (2, '2022'), (3, '2023')], default=3),
        ),
    ]
